name: PR Test Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest ruff mypy flake8

      - name: Run ruff (fast linter/formatter check)
        run: |
          echo "Running ruff..."
          ruff check .

      - name: Run mypy (type checks)
        run: |
          echo "Running mypy..."
            # Configuration in mypy.ini
            mypy badge/ tests/

      - name: Run flake8 (style/linting)
        run: |
          echo "Running flake8..."
          flake8 .

      - name: Run pytest
        run: pytest -q

      - name: Run test checks script (legacy)
        if: always()
        run: python tests/run_checks.py
